version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pariwisata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/pariwisata
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  db_data: